WIP - updates

diff --git a/setup.yaml b/setup.yaml
--- a/setup.yaml
+++ b/setup.yaml
@@ -17,8 +17,6 @@
 
     # Pacman configuration
 
-    # Note to self: the pacman.conf in the Docker image's rootfs disables saving some files (e.g. manpages) silently:
-    # https://github.com/archlinux/archlinux-docker/commit/b6727d838f5ad4d88eaeb34fe5fe9de2fe5cc819
     - name: Update the pacman configuration file
       become: true
       community.general.ini_file:
@@ -32,6 +30,15 @@
         - Color
         - VerbosePkgLists
         - ParallelDownloads = 24
+
+    # Note to self: the pacman.conf in the Docker image's rootfs disables saving some files (e.g. manpages) silently:
+    # https://github.com/archlinux/archlinux-docker/commit/b6727d838f5ad4d88eaeb34fe5fe9de2fe5cc819
+    - name: Remove the NoExtract lines from the end of the pacman configuration file
+      become: true
+      ansible.builtin.lineinfile:
+        path: /etc/pacman.conf
+        state: absent
+        regexp: '^NoExtract\s+='
 
     # Locale configuration
 
@@ -60,6 +67,13 @@
           changed_when: true
 
     # Enable time synchronization
+    - name: Create the /etc/systemd/system/systemd-timesyncd.service.d directory
+      become: true
+      ansible.builtin.file:
+        path: "/etc/systemd/system/systemd-timesyncd.service.d"
+        state: directory
+        mode: '0755'
+
 
     - name: Enable systemd-timesyncd on WSL
       become: true
@@ -108,8 +122,6 @@
           - bat
           - dog
           - ripgrep
-
-    # make sure the .config directory exists
 
     - name: Create the ~/.config directory
       ansible.builtin.file:
@@ -243,88 +255,38 @@
 
     # Terraform configuration
 
-    - name: Install the latest version of terraform and tofu via tenv
-      block:
-        - name: Get the latest release info via the Github API
-          ansible.builtin.uri:
-            url: https://api.github.com/repos/tofuutils/tenv/releases/latest
-            return_content: true
-          register: tenv_release_info
+    - name: Install tenv-bin
+      aur:
+        name: tenv-bin
+        state: present
 
-        - name: Set some helper facts
-          ansible.builtin.set_fact:
-            tenv_latest_browser_download_url: >-
-              {{ tenv_release_info.json
-                 | community.general.json_query('assets[?ends_with(browser_download_url, `amd64.pkg.tar.zst`)]')
-                 | first
-                 | community.general.json_query('browser_download_url') }}
-            tenv_latest_filename: >-
-              {{ tenv_release_info.json
-                 | community.general.json_query('assets[?ends_with(browser_download_url, `amd64.pkg.tar.zst`)]')
-                 | first
-                 | community.general.json_query('name') }}
+    - name: Check if terraform is already installed
+      ansible.builtin.shell:
+        cmd: >
+          tenv tf list
+      register: result_tenv_tf_status
+      changed_when: false
 
-        - name: Download the latest tenv release
-          ansible.builtin.get_url:
-            url: "{{ tenv_latest_browser_download_url }}"
-            dest: "/tmp/{{ tenv_latest_filename }}"
-            mode: "0644"
-          changed_when: false
+    - name: Install terraform
+      ansible.builtin.shell:
+        cmd: >
+          tenv tf install
+      when: result_tenv_tf_status.stdout is defined and result_tenv_tf_status.stdout | length == 0
+      changed_when: true
 
-        - name: Check the downloaded tenv release's version
-          ansible.builtin.shell:
-            cmd:
-              pacman -Qip "/tmp/{{ tenv_latest_filename }}" | awk '/Version/{print $3}'
-          register: tenv_latest_version_temp
-          changed_when: false
+    - name: Check if tofu is already installed
+      ansible.builtin.shell:
+        cmd: >
+          tenv tofu list
+      register: result_tenv_tofu_status
+      changed_when: false
 
-        - name: Set some helper facts
-          ansible.builtin.set_fact:
-            tenv_latest_version: "{{ tenv_latest_version_temp.stdout }}"
-            tenv_installed_version: "{{ (ansible_facts.packages['tenv'] | default([{'version': ''}]))[0].version }}"
-
-        - name: Install the downloaded tenv release
-          become: true
-          community.general.pacman:
-            name: "/tmp/{{ tenv_latest_filename }}"
-            state: present
-          when: >
-            ('tenv' not in ansible_facts.packages) or
-            (tenv_latest_version != tenv_installed_version)
-
-        - name: Remove the installer package
-          ansible.builtin.file:
-            path: "/tmp/{{ tenv_latest_filename }}"
-            state: absent
-          changed_when: false
-
-        - name: Check if terraform is already installed
-          ansible.builtin.shell:
-            cmd: >
-              tenv tf list
-          register: result_tenv_tf_status
-          changed_when: false
-
-        - name: Install terraform
-          ansible.builtin.shell:
-            cmd: >
-              tenv tf install
-          when: result_tenv_tf_status.stdout is defined and result_tenv_tf_status.stdout | length == 0
-          changed_when: true
-
-        - name: Check if tofu is already installed
-          ansible.builtin.shell:
-            cmd: >
-              tenv tofu list
-          register: result_tenv_tofu_status
-          changed_when: false
-
-        - name: Install tofu
-          ansible.builtin.shell:
-            cmd: >
-              tenv tofu install
-          when: result_tenv_tofu_status.stdout is defined and result_tenv_tofu_status.stdout | length == 0
-          changed_when: true
+    - name: Install tofu
+      ansible.builtin.shell:
+        cmd: >
+          tenv tofu install
+      when: result_tenv_tofu_status.stdout is defined and result_tenv_tofu_status.stdout | length == 0
+      changed_when: true
 
     # Docker configuration
 
@@ -367,6 +329,13 @@
           - istio
 
     # 1Password configuration
+
+    - name: Import GPG key for 1password-cli
+      shell: |
+        if ! gpg --list-keys 3FEF9748469ADBE15DA7CA80AC2D62742012EA22; then
+          gpg --recv-keys 3FEF9748469ADBE15DA7CA80AC2D62742012EA22
+        fi
+      changed_when: false
 
     - name: Install 1password-cli and some helper scripts
       block:
